server:
  port: 8088
spring:
  data:
    mongodb:
      uri: ${MONGO_URI}
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082
mongock:
  migration-scan-package: com.innowise.paymentservice.config